import type { SeedDeal, SeedTrend, SeedVideo } from "./types";

/** Fictional demo videos. Posters are local placeholders; no third-party embeds. */
export const videos: SeedVideo[] = [
  {
    title: "Skybound Legends: Tempest — Announcement Trailer",
    slug: "skybound-legends-tempest-announce",
    kind: "trailer",
    provider: "demo-local",
    poster: { src: "/media/videos/tempest-announce.svg", alt: "Tempest expansion trailer poster (demo placeholder)", width: 1280, height: 720, credit: "Demo placeholder art" },
    durationSeconds: 142,
    publishedAt: "2026-07-04T13:30:00.000Z",
    relatedGameSlug: "skybound-legends",
    description: "The Stormcaller class, airship raids and living storms — Tempest arrives October 6. (Fictional demo trailer.)",
  },
  {
    title: "Petal & Blade — Release Date Trailer",
    slug: "petal-and-blade-release-date-trailer",
    kind: "trailer",
    provider: "demo-local",
    poster: { src: "/media/videos/petal-blade-date.svg", alt: "Petal & Blade release date trailer poster (demo placeholder)", width: 1280, height: 720, credit: "Demo placeholder art" },
    durationSeconds: 98,
    publishedAt: "2026-07-03T08:00:00.000Z",
    relatedGameSlug: "petal-and-blade",
    description: "August 14, 2026. Every petal drawn by hand. (Fictional demo trailer.)",
  },
  {
    title: "Emberwilds — Release Window Trailer",
    slug: "emberwilds-release-window-trailer",
    kind: "trailer",
    provider: "demo-local",
    poster: { src: "/media/videos/emberwilds-window.svg", alt: "Emberwilds trailer poster (demo placeholder)", width: 1280, height: 720, credit: "Demo placeholder art" },
    durationSeconds: 115,
    publishedAt: "2026-05-20T10:00:00.000Z",
    relatedGameSlug: "emberwilds",
    description: "Reignite the valley's hearths this September. (Fictional demo trailer.)",
  },
  {
    title: "Chrono Drift — Gameplay Reveal",
    slug: "chrono-drift-gameplay-reveal",
    kind: "gameplay",
    provider: "demo-local",
    poster: { src: "/media/videos/chrono-drift-reveal.svg", alt: "Chrono Drift gameplay reveal poster (demo placeholder)", width: 1280, height: 720, credit: "Demo placeholder art" },
    durationSeconds: 254,
    publishedAt: "2026-04-11T16:00:00.000Z",
    relatedGameSlug: "chrono-drift",
    description: "Seven echoes, one perfect lap — nine minutes of uncut time-loop racing. (Fictional demo video.)",
  },
  {
    title: "Silent Meridian — Story Trailer",
    slug: "silent-meridian-story-trailer",
    kind: "trailer",
    provider: "demo-local",
    poster: { src: "/media/videos/silent-meridian-story.svg", alt: "Silent Meridian story trailer poster (demo placeholder)", width: 1280, height: 720, credit: "Demo placeholder art" },
    durationSeconds: 131,
    publishedAt: "2026-06-15T09:00:00.000Z",
    relatedGameSlug: "silent-meridian",
    description: "Something outside the hull is listening. Hold your breath. (Fictional demo trailer.)",
  },
];

/** Fictional demo deals. All URLs point at example.com; prices are invented. */
export const deals: SeedDeal[] = [
  {
    title: "Starfall: Vanguard — 40% off ahead of Riptide",
    slug: "starfall-vanguard-riptide-sale",
    gameSlug: "starfall-vanguard",
    retailer: "PlayPort Store (demo)",
    url: "https://example.com/store/starfall-vanguard-sale",
    price: 23.99,
    originalPrice: 39.99,
    currency: "USD",
    discountPercent: 40,
    isFree: false,
    startsAt: "2026-07-01T00:00:00.000Z",
    endsAt: "2026-07-15T00:00:00.000Z",
    platformSlugs: ["pc", "playstation", "xbox"],
    note: "Best entry point before the Season 3 flood. Demo pricing — this deal is fictional.",
  },
  {
    title: "Neon Havoc free weekend on mobile",
    slug: "neon-havoc-free-weekend",
    gameSlug: "neon-havoc",
    retailer: "App stores (demo)",
    url: "https://example.com/mobile/neon-havoc-free",
    price: 0,
    originalPrice: 6.99,
    currency: "USD",
    discountPercent: 100,
    isFree: true,
    startsAt: "2026-07-04T00:00:00.000Z",
    endsAt: "2026-07-07T00:00:00.000Z",
    platformSlugs: ["mobile"],
    note: "Full game free through Sunday; progress carries into a purchase. Fictional demo deal.",
  },
  {
    title: "Ironroot Tactics early-access 25% launch-anniversary discount",
    slug: "ironroot-tactics-anniversary-discount",
    gameSlug: "ironroot-tactics",
    retailer: "GameHub (demo)",
    url: "https://example.com/gamehub/ironroot-sale",
    price: 18.74,
    originalPrice: 24.99,
    currency: "USD",
    discountPercent: 25,
    isFree: false,
    startsAt: "2026-06-28T00:00:00.000Z",
    endsAt: "2026-07-12T00:00:00.000Z",
    platformSlugs: ["pc", "handheld"],
    note: "Discounted while the 0.9.4 balance patch is fresh. Fictional demo deal.",
  },
  {
    title: "Skybound Legends base game free for Tempest pre-registrants",
    slug: "skybound-legends-base-free",
    gameSlug: "skybound-legends",
    retailer: "PlayPort Store (demo)",
    url: "https://example.com/store/skybound-free",
    price: 0,
    originalPrice: 29.99,
    currency: "USD",
    discountPercent: 100,
    isFree: true,
    startsAt: "2026-07-04T00:00:00.000Z",
    endsAt: "2026-10-06T00:00:00.000Z",
    platformSlugs: ["pc", "playstation", "xbox", "cloud-gaming"],
    note: "Base game free through Tempest's launch for anyone pre-registering the expansion. Fictional demo deal.",
  },
];

/**
 * Fictional demo trends. `whyTrending` is the required plain-language
 * explanation surfaced next to every trend on the site.
 */
export const trends: SeedTrend[] = [
  {
    title: "Skybound Legends: Tempest",
    slug: "trend-skybound-tempest",
    whyTrending: "Announced yesterday with a firm October date and the game's first new class since launch — the biggest live-service story of the week, spiking engagement and search at once.",
    context: "Horizonworks dated the expansion on July 4 after months of teasing. Pinned by editorial through the announcement cycle.",
    score: 92,
    pinned: true,
    hidden: false,
    manualAdjustment: 10,
    expiresAt: "2026-07-11T00:00:00.000Z",
    relatedArticleSlugs: ["skybound-legends-tempest-expansion-october"],
    relatedGameSlugs: ["skybound-legends"],
  },
  {
    title: "Petal & Blade release date",
    slug: "trend-petal-blade-date",
    whyTrending: "A locked August 14 date after months of silence ended slip speculation, driving heavy search interest and the week's most-shared trailer.",
    context: "Confirmed via press release and trailer on July 3; five-platform simultaneous launch.",
    score: 84,
    pinned: false,
    hidden: false,
    manualAdjustment: 0,
    expiresAt: "2026-08-21T00:00:00.000Z",
    relatedArticleSlugs: ["petal-and-blade-august-release-date", "studio-lantern-interview"],
    relatedGameSlugs: ["petal-and-blade"],
  },
  {
    title: "Chrono Drift delay reports",
    slug: "trend-chrono-drift-delay",
    whyTrending: "Two-source reporting that the Q4 window is internally dead has readers watching for an official statement; engagement velocity is high but the story remains unconfirmed.",
    context: "Editorial reduced this trend's score pending official confirmation — reporting, not announcement.",
    score: 71,
    pinned: false,
    hidden: false,
    manualAdjustment: -8,
    expiresAt: null,
    relatedArticleSlugs: ["chrono-drift-delay-report"],
    relatedGameSlugs: ["chrono-drift"],
  },
  {
    title: "Handheld PC verification wave",
    slug: "trend-handheld-verification",
    whyTrending: "Petal & Blade's battery preset and Ironroot's monthly handheld tuning notes crystallized a platform shift readers have been searching for all week.",
    context: "Slow-burn structural trend; sustained search interest rather than a single spike.",
    score: 63,
    pinned: false,
    hidden: false,
    manualAdjustment: 0,
    expiresAt: null,
    relatedArticleSlugs: ["opinion-handheld-pcs-default", "petal-and-blade-august-release-date"],
    relatedGameSlugs: ["petal-and-blade", "ironroot-tactics"],
  },
  {
    title: "Ashen Covenant leak fallout",
    slug: "trend-ashen-covenant-leak",
    whyTrending: "The unverified fortress-system clip is the week's most-discussed video despite — or because of — the studio's silence. High engagement, low source authority, scored accordingly.",
    context: "Trend score reflects the low authority of the sole source; will be re-evaluated if the studio comments.",
    score: 58,
    pinned: false,
    hidden: false,
    manualAdjustment: -5,
    expiresAt: "2026-07-15T00:00:00.000Z",
    relatedArticleSlugs: ["ashen-covenant-footage-leak"],
    relatedGameSlugs: ["ashen-covenant"],
  },
  {
    title: "Extraction genre comeback",
    slug: "trend-extraction-comeback",
    whyTrending: "Riptide's permanent map flood plus our consequence-architecture analysis pushed the genre back into the discourse — search interest is at a six-month high in demo data.",
    context: "Analysis-driven trend; editorial significance weighted up.",
    score: 55,
    pinned: false,
    hidden: false,
    manualAdjustment: 5,
    expiresAt: null,
    relatedArticleSlugs: ["extraction-shooters-second-wind-analysis", "starfall-vanguard-season-3-riptide"],
    relatedGameSlugs: ["starfall-vanguard"],
  },
];
