import type { SeedGame, SeedImage, SeedReleaseDate } from "./types";

const SYNCED = "2026-07-01T08:00:00.000Z";

const img = (path: string, alt: string, w = 1280, h = 720, credit = "Demo placeholder art — Gaming Pulse"): SeedImage => ({
  src: path,
  alt,
  width: w,
  height: h,
  credit,
});

const cover = (slug: string, name: string): SeedImage =>
  img(`/media/games/${slug}-cover.svg`, `${name} cover art (demo placeholder)`, 600, 800);

const hero = (slug: string, name: string): SeedImage =>
  img(`/media/games/${slug}-hero.svg`, `${name} key art (demo placeholder)`, 1920, 820);

const shots = (slug: string, name: string, n: number): SeedImage[] =>
  Array.from({ length: n }, (_, i) =>
    img(`/media/games/${slug}-shot-${i + 1}.svg`, `${name} screenshot ${i + 1} (demo placeholder)`),
  );

/** All games are fictional demo entries. */
export const games: SeedGame[] = [
  {
    name: "Starfall: Vanguard",
    slug: "starfall-vanguard",
    externalDatabaseId: "demo-igdb-90001",
    summary: "A squad-based sci-fi extraction shooter set on a shattering ringworld, where every raid permanently reshapes the orbital map.",
    description: "Starfall: Vanguard (fictional demo game) drops three-player squads onto the fracturing ringworld of Cerule. Extract salvage before orbital collapse windows close, invest it in your frontier outpost, and watch the persistent map shift for every player on your shard. Season 2, 'Undertow', added underwater biomes and the game's first raid-scale event.",
    cover: cover("starfall-vanguard", "Starfall: Vanguard"),
    heroArtwork: hero("starfall-vanguard", "Starfall: Vanguard"),
    screenshots: shots("starfall-vanguard", "Starfall: Vanguard", 4),
    trailerSlugs: ["starfall-vanguard-season-2-trailer"],
    genres: ["Shooter", "Extraction"],
    themes: ["Sci-fi", "Survival"],
    platformSlugs: ["pc", "playstation", "xbox"],
    developerSlug: "nova-forge-studios",
    publisherSlug: "meridian-interactive",
    franchise: "Starfall",
    releaseStatus: "released",
    ageRatings: ["ESRB T", "PEGI 16"],
    gameModes: ["Online co-op", "PvPvE"],
    officialWebsite: "https://example.com/starfall-vanguard",
    storeLinks: [
      { store: "PlayPort Store (demo)", url: "https://example.com/store/starfall-vanguard" },
      { store: "GameHub (demo)", url: "https://example.com/gamehub/starfall-vanguard" },
    ],
    trendingScore: 68,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Emberwilds",
    slug: "emberwilds",
    externalDatabaseId: "demo-igdb-90002",
    summary: "A cozy open-world crafting adventure about reigniting the hearths of a valley that forgot fire.",
    description: "Emberwilds (fictional demo game) hands you a tinderbox and a valley in perpetual autumn dusk. Befriend fireflies, restore hearths to wake sleeping villages, and shape your own glade with a deep but gentle crafting system. Willow & Wren says the whole game can be finished without combat.",
    cover: cover("emberwilds", "Emberwilds"),
    heroArtwork: hero("emberwilds", "Emberwilds"),
    screenshots: shots("emberwilds", "Emberwilds", 4),
    trailerSlugs: ["emberwilds-release-window-trailer"],
    genres: ["Adventure", "Simulation"],
    themes: ["Cozy", "Nature"],
    platformSlugs: ["nintendo", "pc"],
    developerSlug: "willow-and-wren-games",
    publisherSlug: "willow-and-wren-games",
    franchise: null,
    releaseStatus: "upcoming",
    ageRatings: ["ESRB E", "PEGI 3"],
    gameModes: ["Single-player"],
    officialWebsite: "https://example.com/emberwilds",
    storeLinks: [{ store: "eShop (demo)", url: "https://example.com/eshop/emberwilds" }],
    trendingScore: 74,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Chrono Drift",
    slug: "chrono-drift",
    externalDatabaseId: "demo-igdb-90003",
    summary: "Arcade racing meets time loops: rewind the track, race your echoes, and stack seven ghosts of yourself into one perfect lap.",
    description: "Chrono Drift (fictional demo game) is Redline Arcadia's answer to the question 'what if a racing line was a puzzle?'. Each rewind spawns an echo that drives your previous lap, and the campaign's hardest medals require choreographing all seven echoes at once.",
    cover: cover("chrono-drift", "Chrono Drift"),
    heroArtwork: hero("chrono-drift", "Chrono Drift"),
    screenshots: shots("chrono-drift", "Chrono Drift", 3),
    trailerSlugs: ["chrono-drift-gameplay-reveal"],
    genres: ["Racing", "Puzzle"],
    themes: ["Time loop", "Neon"],
    platformSlugs: ["pc", "playstation", "xbox"],
    developerSlug: "redline-arcadia",
    publisherSlug: "meridian-interactive",
    franchise: null,
    releaseStatus: "upcoming",
    ageRatings: ["ESRB E10+", "PEGI 7"],
    gameModes: ["Single-player", "Online multiplayer"],
    officialWebsite: "https://example.com/chrono-drift",
    storeLinks: [{ store: "PlayPort Store (demo)", url: "https://example.com/store/chrono-drift" }],
    trendingScore: 55,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Ashen Covenant",
    slug: "ashen-covenant",
    externalDatabaseId: "demo-igdb-90004",
    summary: "A dark-fantasy action RPG where every death feeds the covenant you swore to destroy.",
    description: "Ashen Covenant (fictional demo game) is Blackspire Forge's most ambitious project: a soulslike where the antagonist faction literally grows stronger from your failures, remodeling its fortresses with each death. Almost everything about it remains under wraps.",
    cover: cover("ashen-covenant", "Ashen Covenant"),
    heroArtwork: hero("ashen-covenant", "Ashen Covenant"),
    screenshots: shots("ashen-covenant", "Ashen Covenant", 2),
    trailerSlugs: [],
    genres: ["Action RPG", "Soulslike"],
    themes: ["Dark fantasy"],
    platformSlugs: ["pc", "playstation", "xbox"],
    developerSlug: "blackspire-forge",
    publisherSlug: "meridian-interactive",
    franchise: null,
    releaseStatus: "upcoming",
    ageRatings: ["Rating pending"],
    gameModes: ["Single-player"],
    officialWebsite: "https://example.com/ashen-covenant",
    storeLinks: [],
    trendingScore: 61,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Neon Havoc",
    slug: "neon-havoc",
    externalDatabaseId: "demo-igdb-90005",
    summary: "A one-thumb roguelite brawler with console-grade combat depth, built natively for phones.",
    description: "Neon Havoc (fictional demo game) compresses a character-action combo system into a single thumb. Pocket Thunder's runs last five minutes, the meta-progression respects your time, and there is no energy system — a premium price and that's it.",
    cover: cover("neon-havoc", "Neon Havoc"),
    heroArtwork: hero("neon-havoc", "Neon Havoc"),
    screenshots: shots("neon-havoc", "Neon Havoc", 3),
    trailerSlugs: [],
    genres: ["Roguelite", "Brawler"],
    themes: ["Cyberpunk", "Neon"],
    platformSlugs: ["mobile"],
    developerSlug: "pocket-thunder",
    publisherSlug: "pocket-thunder",
    franchise: null,
    releaseStatus: "released",
    ageRatings: ["ESRB E10+", "PEGI 12"],
    gameModes: ["Single-player"],
    officialWebsite: "https://example.com/neon-havoc",
    storeLinks: [{ store: "App stores (demo)", url: "https://example.com/mobile/neon-havoc" }],
    trendingScore: 47,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Silent Meridian",
    slug: "silent-meridian",
    externalDatabaseId: "demo-igdb-90006",
    summary: "A VR narrative thriller aboard a research submarine where sound is both your interface and your enemy.",
    description: "Silent Meridian (fictional demo game) traps you aboard the submarine Meridian with a crew that communicates only in whispers — because something outside the hull listens. Deepcurrent's audio-first design uses your actual microphone: hold your breath, and your character does too.",
    cover: cover("silent-meridian", "Silent Meridian"),
    heroArtwork: hero("silent-meridian", "Silent Meridian"),
    screenshots: shots("silent-meridian", "Silent Meridian", 3),
    trailerSlugs: ["silent-meridian-story-trailer"],
    genres: ["Adventure", "Horror"],
    themes: ["Thriller", "Deep sea"],
    platformSlugs: ["vr", "pc"],
    developerSlug: "deepcurrent-studios",
    publisherSlug: "meridian-interactive",
    franchise: null,
    releaseStatus: "upcoming",
    ageRatings: ["ESRB M", "PEGI 18"],
    gameModes: ["Single-player"],
    officialWebsite: "https://example.com/silent-meridian",
    storeLinks: [{ store: "VR storefronts (demo)", url: "https://example.com/vr/silent-meridian" }],
    trendingScore: 42,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Ironroot Tactics",
    slug: "ironroot-tactics",
    externalDatabaseId: "demo-igdb-90007",
    summary: "A turn-based strategy game about botanical warfare — grow your army, literally, from the terrain you fight on.",
    description: "Ironroot Tactics (fictional demo game) replaces unit production with cultivation: seed the battlefield, and terrain type, weather and time all change what grows. Quiet Anvil has run an unusually transparent early access, shipping monthly balance letters.",
    cover: cover("ironroot-tactics", "Ironroot Tactics"),
    heroArtwork: hero("ironroot-tactics", "Ironroot Tactics"),
    screenshots: shots("ironroot-tactics", "Ironroot Tactics", 4),
    trailerSlugs: [],
    genres: ["Strategy", "Turn-based"],
    themes: ["Nature", "War"],
    platformSlugs: ["pc", "handheld"],
    developerSlug: "quiet-anvil",
    publisherSlug: "quiet-anvil",
    franchise: null,
    releaseStatus: "early-access",
    ageRatings: ["ESRB E10+", "PEGI 7"],
    gameModes: ["Single-player", "Online multiplayer"],
    officialWebsite: "https://example.com/ironroot-tactics",
    storeLinks: [{ store: "GameHub (demo)", url: "https://example.com/gamehub/ironroot-tactics" }],
    trendingScore: 38,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Skybound Legends",
    slug: "skybound-legends",
    externalDatabaseId: "demo-igdb-90008",
    summary: "A live-service action MMO of floating islands, airships and guild-built sky cities.",
    description: "Skybound Legends (fictional demo game) has spent three years growing from a modest launch into Horizonworks' flagship. Guilds terraform their own floating islands, and the upcoming 'Tempest' expansion introduces storm-chasing world events and the first new class since launch.",
    cover: cover("skybound-legends", "Skybound Legends"),
    heroArtwork: hero("skybound-legends", "Skybound Legends"),
    screenshots: shots("skybound-legends", "Skybound Legends", 4),
    trailerSlugs: ["skybound-legends-tempest-announce"],
    genres: ["MMO", "Action"],
    themes: ["Fantasy", "Sky islands"],
    platformSlugs: ["pc", "playstation", "xbox", "cloud-gaming"],
    developerSlug: "horizonworks",
    publisherSlug: "horizonworks",
    franchise: "Skybound",
    releaseStatus: "released",
    ageRatings: ["ESRB T", "PEGI 12"],
    gameModes: ["MMO", "Online co-op"],
    officialWebsite: "https://example.com/skybound-legends",
    storeLinks: [
      { store: "PlayPort Store (demo)", url: "https://example.com/store/skybound-legends" },
      { store: "CloudPlay (demo)", url: "https://example.com/cloud/skybound-legends" },
    ],
    trendingScore: 82,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Petal & Blade",
    slug: "petal-and-blade",
    externalDatabaseId: "demo-igdb-90009",
    summary: "A hand-drawn metroidvania where your sword is a living cherry branch that blooms as you master it.",
    description: "Petal & Blade (fictional demo game) pairs Studio Lantern's frame-by-frame animation with a combat system that grows: every mastered technique makes your branch-blade bloom new petals, each a modifier you can spend or keep. It ships August 14, 2026 on everything.",
    cover: cover("petal-and-blade", "Petal & Blade"),
    heroArtwork: hero("petal-and-blade", "Petal & Blade"),
    screenshots: shots("petal-and-blade", "Petal & Blade", 4),
    trailerSlugs: ["petal-and-blade-release-date-trailer"],
    genres: ["Metroidvania", "Action"],
    themes: ["Hand-drawn", "Folklore"],
    platformSlugs: ["pc", "playstation", "xbox", "nintendo", "handheld"],
    developerSlug: "studio-lantern",
    publisherSlug: "meridian-interactive",
    franchise: null,
    releaseStatus: "upcoming",
    ageRatings: ["ESRB E10+", "PEGI 7"],
    gameModes: ["Single-player"],
    officialWebsite: "https://example.com/petal-and-blade",
    storeLinks: [
      { store: "PlayPort Store (demo)", url: "https://example.com/store/petal-and-blade" },
      { store: "eShop (demo)", url: "https://example.com/eshop/petal-and-blade" },
    ],
    trendingScore: 77,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
  {
    name: "Circuit Breakers 2",
    slug: "circuit-breakers-2",
    externalDatabaseId: "demo-igdb-90010",
    summary: "The sequel to the arena-shooter esports staple, rebuilt on rollback netcode with a spectator-first broadcast mode.",
    description: "Circuit Breakers 2 (fictional demo game) is Voltcore's bid to keep its esport alive for another decade: 128-tick servers, a built-in broadcast director, and a promise that every original map returns remade. Closed beta begins this winter.",
    cover: cover("circuit-breakers-2", "Circuit Breakers 2"),
    heroArtwork: hero("circuit-breakers-2", "Circuit Breakers 2"),
    screenshots: shots("circuit-breakers-2", "Circuit Breakers 2", 2),
    trailerSlugs: [],
    genres: ["Shooter", "Arena"],
    themes: ["Esports", "Sci-fi"],
    platformSlugs: ["pc"],
    developerSlug: "voltcore-games",
    publisherSlug: "voltcore-games",
    franchise: "Circuit Breakers",
    releaseStatus: "upcoming",
    ageRatings: ["Rating pending"],
    gameModes: ["Online multiplayer"],
    officialWebsite: "https://example.com/circuit-breakers-2",
    storeLinks: [],
    trendingScore: 44,
    dataSource: "manual-demo",
    lastSynchronizedAt: SYNCED,
  },
];

/** 16 fictional release-date entries covering every precision level and kind. */
export const releaseDates: SeedReleaseDate[] = [
  { id: "rd-01", gameSlug: "petal-and-blade", platformSlugs: ["pc", "playstation", "xbox", "nintendo", "handheld"], region: "worldwide", date: "2026-08-14", precision: "exact", kind: "full", confirmed: true, note: "Simultaneous worldwide launch confirmed by Studio Lantern." },
  { id: "rd-02", gameSlug: "emberwilds", platformSlugs: ["nintendo", "pc"], region: "worldwide", date: "2026-09-17", precision: "exact", kind: "full", confirmed: true },
  { id: "rd-03", gameSlug: "chrono-drift", platformSlugs: ["pc", "playstation", "xbox"], region: "worldwide", date: "2026-11-01", precision: "quarter", kind: "full", confirmed: false, note: "Q4 2026 window; a report suggests possible slip to early 2027." },
  { id: "rd-04", gameSlug: "silent-meridian", platformSlugs: ["vr", "pc"], region: "worldwide", date: "2026-11-01", precision: "month", kind: "full", confirmed: true, note: "November 2026, exact day to be announced." },
  { id: "rd-05", gameSlug: "ashen-covenant", platformSlugs: ["pc", "playstation", "xbox"], region: "worldwide", date: "2027-01-01", precision: "year", kind: "full", confirmed: false, note: "2027 target per publisher earnings call (demo)." },
  { id: "rd-06", gameSlug: "circuit-breakers-2", platformSlugs: ["pc"], region: "worldwide", date: "2026-12-10", precision: "exact", kind: "early-access", confirmed: true, note: "Closed beta / early access start." },
  { id: "rd-07", gameSlug: "circuit-breakers-2", platformSlugs: ["pc"], region: "worldwide", date: "2027-04-01", precision: "quarter", kind: "full", confirmed: false, note: "1.0 targeted for Q2 2027." },
  { id: "rd-08", gameSlug: "skybound-legends", platformSlugs: ["pc", "playstation", "xbox", "cloud-gaming"], region: "worldwide", date: "2026-10-06", precision: "exact", kind: "expansion", confirmed: true, note: "'Tempest' expansion." },
  { id: "rd-09", gameSlug: "ironroot-tactics", platformSlugs: ["pc"], region: "worldwide", date: "2025-11-12", precision: "exact", kind: "early-access", confirmed: true, note: "Early access began November 2025." },
  { id: "rd-10", gameSlug: "ironroot-tactics", platformSlugs: ["pc", "handheld"], region: "worldwide", date: null, precision: "tba", kind: "full", confirmed: false, note: "1.0 date not announced." },
  { id: "rd-11", gameSlug: "starfall-vanguard", platformSlugs: ["pc", "playstation", "xbox"], region: "worldwide", date: "2026-03-05", precision: "exact", kind: "full", confirmed: true, note: "Launched March 2026." },
  { id: "rd-12", gameSlug: "starfall-vanguard", platformSlugs: ["pc", "playstation", "xbox"], region: "worldwide", date: "2026-08-20", precision: "exact", kind: "dlc", confirmed: true, note: "Season 3 'Riptide' content drop." },
  { id: "rd-13", gameSlug: "neon-havoc", platformSlugs: ["mobile"], region: "worldwide", date: "2026-06-11", precision: "exact", kind: "full", confirmed: true },
  { id: "rd-14", gameSlug: "emberwilds", platformSlugs: ["nintendo"], region: "jp", date: "2026-10-01", precision: "month", kind: "full", confirmed: true, note: "Japanese physical edition follows in October 2026." },
  { id: "rd-15", gameSlug: "chrono-drift", platformSlugs: ["pc"], region: "worldwide", date: "2026-09-01", precision: "month", kind: "early-access", confirmed: false, note: "Time-trial demo weekend planned for September (unconfirmed)." },
  { id: "rd-16", gameSlug: "petal-and-blade", platformSlugs: ["pc"], region: "worldwide", date: "2027-03-01", precision: "quarter", kind: "dlc", confirmed: false, note: "Post-launch story chapter, Q1 2027 window." },
];
